services:
  - type: web
    name: puter-ai-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/src/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome
